### ISSUE TITLE
Datenschutzerklärung

### ISSUE THREAD

**Issue by gesine57** [serlo/serlo-abc#369]
Es soll die Möglichkeit geben Datenschutzerklärung und Nutzungsbedingungen (Tracking) zuzustimmen oder diese abzulehnen. Wobei der Ablehnungsbutton unscheinbarer als der Zustimmungsbutton sein soll. - Ob User, die abgelehnt haben, beim Tracking mitgezählt werden, ist noch festzulegen.

**Comment by Knorrke** [comment]
closed in #370 - for now we don't use a button to decline the policy, because of simplicity for the users (especially since they probably can't read it...). However data is only collected after clicking `OK`.
